project:
  type: manuscript
  output-dir: _manuscript
  render:
    - index.qmd

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  typst: default
  jats: default
  docx: default

execute:
  freeze: true
bibliography: references.bib
