---
format: typst
---

# Adult ADHD Diagnostic Tools for Search

-   Adaptive Behavior Assessment System, 3rd ed (ABAS-3)
-   Advanced Clinical Solutions (ACS): Word Choice Test, Test of Premorbid Functioning (TOPF), Social Cognition
-   Beck Anxiety Inventory (BAI)
-   Beck Depression Inventory, 2nd ed (BDI-2)
-   Behavioral Assessment System for Children, 3rd ed,  Self-Report of Personality, Adolescent (BASC-3 SRP Adolescent)
-   Behavioral Assessment System for Children, 3rd ed, Parent Rating Scales, Adolescent (BASC-3 PRS Adolescent)
-   Behavioral Assessment System for Children, 3rd ed, Self-Report of Personality, College (BASC-3 SRP College)
-   Behavioral Assessment System for Children, 3rd ed, Teacher Rating Scales, Adolescent (BASC-3 TRS Adolescent)
-   Brown Executive Function/Attention Scales, Self-Report (Brown EF/A Self)
-   California Verbal Learning Test, 3rd ed (CVLT-3), Standard Form
-   California Verbal Learning Test, 3rd ed, Brief Form (CVLT-3 Brief)
-   California Verbal Learning Test, Child ed (CVLT-C)
-   Childhood Autism Rating Scale, 2nd ed (CARS-2)
-   Childhood Autism Rating Scale, 2nd ed, High-Functioning Version (CARS-2 HF)
-   Clinical Evaluation of Language Fundamentals, 5th ed, Ages 9-21 (CELF-5)
-   Comprehensive Executive Function Inventory, Adult, Observer (CEFI Adult Observer)
-   Comprehensive Executive Function Inventory, Adult, Self-Report Form (CEFI Adult Self-Report)
-   Conners' Adult ADHD Diagnostic Interview for DSM-IV, Part I: History (CAADID Part 1)
-   Conners' Adult ADHD Diagnostic Interview for DSM-IV, Part II (CAADID Part 2)
-   Conners' Adult ADHD Rating Scales--Observer Report: Long Version (CAARS--O:L)
-   Conners' Adult ADHD Rating Scales--Self-Report: Long Version (CAARS--S:L)
-   Conners' Adult ADHD Rating Scales, 2nd ed, Observer (CAARS-2 Observer)
-   Conners' Adult ADHD Rating Scales, 2nd ed, Self-Report (CAARS-2 Self-Report)
-   Delis-Kaplan Executive Function System (D-KEFS)
-   Dot Counting Test (DCT)
-   Grooved Pegboard Test
-   Kaufman Test of Educational Achievement, 3rd ed (KTEA-3)
-   NEPSY-II Developmental Neuropsychological Battery
-   Neuropsychological Assessment Battery (NAB): Attention, Language, Memory, Spatial, and Executive Functions Modules
-   NIH Executive Abilities--Measures and Instruments for Neurobehavioral Evaluation and Research (NIH EXAMINER)
-   Personality Assessment Inventory (PAI)
-   PROMIS Sleep Assessments Pediatric Parent Proxy
-   Repeatable Battery for the Assessment of Neuropsychological Status (RBANS)
-   Rey-Osterrieth Complex Figure Test (ROCFT)
-   Trail Making Test (TMT)
-   Wechsler Abbreviated Scale of Intelligence, 2nd ed (WASI-2)
-   Wechsler Adult Intelligence Scale, 4th ed (WAIS-4, WAIS-IV)
-   Wechsler Individual Achievement Test, 4th ed (WIAT-4)
-   Wechsler Intelligence Scale for Children, 5th ed (WISC-5)
-   Wechsler Memory Scale, 4th ed (WMS-4)
-   Wide Range Achievement Test, 5th ed, (WRAT-5)
-   Adult ADHD Rating Scale (ADHD-RS)
-   Brown ADD scales
-   Continuous Performance Tests (e.g. Conners CPT, QB Test, TOVA, etc)
-   Wender Utah Adult ADHD Scale (something like that)
