Dear J and Joey,

I’m writing to ask your help for the Adult ADHD application. If you don’t have the time for this, please tell me so that I don’t count on you to help but then you’re unable. If you’re able, I need your input before early Sunday morning this week, preferably even before the weekend.

The review, as you know, has 3 components – diagnosis, management/treatment, and stimulant diversion.  The application background section is very important because it sets the frame for the review and guides the search for publications to be reviewed. The background section has 2 important components, each 1-2 pages (only) in length – (1) key decisional dilemma (ie, what do patients, clinicians, and stakeholders care about and need to decide in diagnosis and caring for an adult who may have ADHD?), and (2) current controversies and challenges in doing so.
 
I’ll work on all 3 components of both background sections but would like your help taking the lead with diagnosis (Joey) and diversion (J). I’ll search for and skim review papers on each topic. I’d like to as you to go through the very rough, preliminary lit search for individual papers in each area and provide bullet points on back ground sections 1 & 2 above. If you can provide the citation for each bullet point in a marginal comment bubble, that would be helpful. Most of the papers in the lit search are not relevant and many pertain only to youth, not adults, so skimming them doesn’t take nearly as long as it might first appear.
 
Here are some general, generic questions/issues often encountered in each of the background sections to give you and idea for what may be relevant to look for:
 
## Key decisional dilemma for the evidence review
The decisional dilemma section can be 1-2 pages long. Focus is on relevance to practice, between which alternatives do patients and providers have to choose? This is not about the research so much as what people in practice need to know. What do they need to consider whether and when they provide treatment. Examples are: is the diagnosis problematic, are there different practices, do we know which treatment formats work, who should initiate the treatment, is there conflicting treatment advice or has our approach changed over time, do we know enough about the effects of the treatment to make informed decisions, are there unintended consequences of treating or not treating, are all treatment options typically known, is a clinical diagnosis always followed by treatment, do all people respond the same, is the treatment effect likely dependent on patient characteristics, are there cultural differences that need to be considered, are there groups of people for whom we do not know enough at this point?

Diagnosis: Joey (& Brad)
Treatment: Brad
Diversion: J (& Brad)
 
## Controversies & Challenges
The challenges section can be 1-2 pages long. Focus is on the literature base, but at a high level. Some ideas are: are there distinct schools of thought, is there conflicting advice, is the nature of condition unclear and does that have consequences for screening and treatment, is there too much clinical judgement involved in the diagnosis or decision to treat which makes samples difficult to compare, are there differences in how rigorous treatments are assessed compared to other treatments, do we know anything about the comparative effectiveness of treatments (which alternative is better) or not yet (or does it depend), are there patient characteristics that influence screening, diagnosing, or the decision to treat, are there cultural aspects that influence screening, the diagnosis, and the treatment; can we use the international literature for the evidence review or is there something US-specific about the topic; is there agreement in the scientific literature about outcomes and are outcomes comparable be
 
Diagnosis: Joey (& Brad)
Treatment: Brad
Diversion: J (& Brad)
 
Please let me know today if you’ll be able to help with your section. If not, that is fine, but I need to know one way or the other, please.
 
Thanks
brad
